config/routes.rb
Rails.application.routes.draw do
  
root "patients#index"

  resources :doctors 
  resources :patients do
    resources :appointments 
  end
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :doctors, through: :appointments
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  
  def index
    @patient = Patient.find(params[:patient_id])
    @appointment = @patient.appointments.new
    @prevents = @patient.appointments.where(role: "preventative")
    @checks = @patient.appointments.where(role: "check up")
    @emers = @patient.appointments.where(role: "emergency")
  end


def show
  end

def new
  @patient = Patient.find(params[:patient_id])
  # grab a list of users who are not enrolled in the course
  @appointment = appointment.new
end

def create
  @patient = Patient.find(params[:patient_id])
  @appointment = @patient.appointment.new(appointment_params)
  if @appointment.save
    redirect_to patient_appointments_path(@patient)
  else
    render :new
  end
end

def destroy
  @patient = Patient.find(params[:patient_id])
  @patient.appointments.find(params[:id]).destroy
  redirect_to patient_appointments_path(@patient)
end

private

def appointment_params
  params.require(:appointment).permit(:doctor_id, :role)
end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :destroy]
  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end
  
  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to @doctor
    else
      render :new
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  
  def index
  @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
   
  end

  def new
  @patient = Patient.new
  end

  def create
    
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to patient_path
    else
      render :new
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to patients_path
  end

private
    
  def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
<h1><%= @patient.name%> Appointments</h1>
<%= link_to 'Make an Appointment' , new_patient_appointment_path(@patient)%>




 <h2>Preventative</h2>
<ul>
  <% @prevents.each do |prev| %>
    <li>
      <%= prev.doctor.first_name%>
      <br />
      <%= link_to 'Remove', patient_appointment_path(@patient, prev), method: :delete %>
    </li>
  <% end %>
</ul>
<h2>Check ups</h2>
<ul>
  <% @checks.each do |check| %>
    <li>
      <%= check.doctor.first_name %>
      <br />
      <%= link_to 'Remove', patient_appointment_path(@patient, prev), method: :delete %>
    </li>
 <% end %>
</ul>
<h2>Emergencies</h2>
<ul>
  <% @emers.each do |emer| %>
    <li>
      <%= emer.doctor.first_name %>
      <br />
    <%= link_to 'Remove', patient_appointment_path(@patient, prev), method: :delete %>
   </li>
 <% end %>
</ul>

app/views/doctors/index.html.erb
<h3>This is the Patients Doctor(s)<h3>

<ul>
  <% @doctors.each do |doctor| %>
    <li><%= link_to "#{doctor.first_name} #{doctor.last_name}" ,doctor %></li>
 
  <% end %>
</ul>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>Find me in app/views/doctors/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
 <h1>Current Patients</h1>
<%= link_to 'Add a patient', new_patient_path %>


 <ul>
  <% @patients.each do |patient| %>
    <li><%= link_to patient.name, patient%>
  <%= link_to 'Update', patient_path(patient) %>
  <%= link_to 'Remove', patient_path(patient),method: :delete%></li> 
  <% end %>
</ul>


  
 

app/views/patients/new.html.erb
<h1>Add a Patient</h1>
<%= form_with(model: @patient, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Patient Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/patients/show.html.erb
 <h1><%= @patient.name %></h1>
<hr />
<br />
<%= link_to 'Appointments', patient_appointments_path(@patient) %>